# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fq7EtwRotcPt4ZGIowS5yZg2vmlXPaAZ
"""

#!/usr/bin/python3.8
print("content-type: text/html")
print()

import cgi
import subprocess
from numpy import random
print("<html>")
print("<head><b> <title> My Program </title></b></head>")
print("<h1> <b> Welcome to My Python Script </b></h1>")
print("<body>")

form=cgi.FieldStorage()

if password="passwd"):
	print("Prassword was successful\n")
	print("Welcome back "+name+" !")
	x=form.getvalue("app")
	li=x.split()
	li=li.lower()
	if "date" in li:
		pd=subprocess.getoutput("date")
		print("Today's date:{}".fomat(pd))
	elif ("cal" in li) or ("calender" in li):
		cal=subprocess.getoutput("cal")
		print("Calender: {}".format(cal))
	elif "docker" in li:
		if form.getvalue("cname"):
			k=form.getvalue("cname")
			if form.getvalue("run"):
				ru="docker run -it --name "+cname+" "+osname
				r=subprocess.getoutput(ru)
				print(r)
				print("container was successfully created using the name: {}".format(cname))
				
			if form.getvalue("start"):
				su="docker start "+cname
				s=subprocess.getoutput(su)
				print(s)
				print("{} container was successfully started".format(cname))
				
			if form.getvalue("rs"):
				res="docker run -it --name "+cname+" "+osname
				sr=subprocess.getoutput(res)
				print(sr)
				print("container was successfully created using the name: {}".format(cname))
				str="docker start "+cname
				st=subprocess.getoutput(str)
				print(st)
				print("container was successfully started")
		else:
			osnu=random.randint(100)
			osna="os"+osnu
			osn="docker run -it --name "+osna+" ubuntu:16.04"
			osu=subprocess.getoutput(osn)
			print(osu)
			print("container was successfully created with ubuntu:16.04 under the name:{}.".format(osna)



	else:
		print("Application not found")
		print("Try again")


else:
	print("Invalid Credentials")
	print("Try again")

print('<form method ="post" action="script.py">')
print('<p>Name: <input type="text" name="name" /></p>')
print('<p> Password: <input type="password" name="password"/> </p>')
print('Enter the application you would like to run <input type="text" name="app" /> Application')
print('<h5> Optional: (for docker only)</h5>')
print('<p> Enter the docker container details </p>')
print(Container name <input type="text" name="cname" />')
print('Os name <input type="text" name="osname"/>')
print('<input type="checkbox" name="run"/> Run docker')
print('<input type="checkbox" name="start"/> Start docker')
print('<input type="checkbox" name="rs"/> Run & Start docker')
print('<select name="osname"><option> ubuntu:16.04 </option><option> centos:7</option> </select>')
print('<input type="submit" value="Submut"/>')
print("</form>")
print("</body>")
print("</html>")